 export const BASE_URL = "http://172.30.1.4:8180/qleaca/api";
 export const BASE_URL_OTH = "https://172.30.1.4:8443/qleaca/api";
//export const BASE_URL = "http://localhost:8080/qle/api";
//export const BASE_URL_OTH = "https://localhost:8443/qle/api";

export const COMMON_CONFIG = "COMMON_CONFIG";

export const PHONE = /^[0-9\- ]{10}$/;
export const dZIPCODE = /(^\d{5}$)|(^\d{5}-\d{4}$)/;
export const ZIPCODE = /(^\d{5}$)|(^\d{5}-\d{4}$)/;
export const EINNUMBER = /(^\d{9})|(^\d{3}-\d{2}-\d{4}$)|(^[1-9]\d?-\d{7}$)/;
export const STATE = /^(?=.*[A-Z])/;
export const ALPHABETS = /^[aA-zZ\s]|[ ,]+$/;
export const SPECIAL = /^'?\p{L}+(?:[' ]\p{L}+)*'?$/u;

export enum loginTypes {
  FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST",
  FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS",
  FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE",
  LOGGED_INFO = "LOGGED_INFO",
}

export enum forgotPwdTypes {
  FETCH_FORGOTPWD_REQUEST = "FETCH_FORGOTPWD_REQUEST",
  FETCH_FORGOTPWD_SUCCESS = "FETCH_FORGOTPWD_SUCCESS",
  FETCH_FORGOTPWD_FAILURE = "FETCH_FORGOTPWD_FAILURE",
  FORGOTPWD_INFO = "FORGOTPWD_INFO",
}

export enum addRoleTypes {
  FETCH_ADDROLE_REQUEST = "FETCH_ADDROLE_REQUEST",
  FETCH_ADDROLE_SUCCESS = "FETCH_ADDROLE_SUCCESS",
  FETCH_ADDROLE_FAILURE = "FETCH_ADDROLE_FAILURE",
  ADDROLE_INFO = "ADDROLE_INFO",
}

export enum allRolesTypes {
  FETCH_ALLROLES_REQUEST = "FETCH_ALLROLES_REQUEST",
  FETCH_ALLROLES_SUCCESS = "FETCH_ALLROLES_SUCCESS",
  FETCH_ALLROLES_FAILURE = "FETCH_ALLROLES_FAILURE",
  ALLROLES_INFO = "ALLROLES_INFO",
}

export enum editRoleTypes {
  FETCH_EDITROLE_REQUEST = "FETCH_EDITROLE_REQUEST",
  FETCH_EDITROLE_SUCCESS = "FETCH_EDITROLE_SUCCESS",
  FETCH_EDITROLE_FAILURE = "FETCH_EDITROLE_FAILURE",
  EDITROLE_INFO = "EDITROLE_INFO",
}

export enum delRoleTypes {
  FETCH_DELROLE_REQUEST = "FETCH_DELROLE_REQUEST",
  FETCH_DELROLE_SUCCESS = "FETCH_DELROLE_SUCCESS",
  FETCH_DELROLE_FAILURE = "FETCH_DELROLE_FAILURE",
  DELROLE_INFO = "DELROLE_INFO",
}

export enum getRoleTypes {
  FETCH_GETROLE_REQUEST = "FETCH_GETROLE_REQUEST",
  FETCH_GETROLE_SUCCESS = "FETCH_GETROLE_SUCCESS",
  FETCH_GETROLE_FAILURE = "FETCH_GETROLE_FAILURE",
  GETROLE_INFO = "GETROLE_INFO",
}

export enum allPrivilegesTypes {
  FETCH_ALLPRIVILEGES_REQUEST = "FETCH_ALLPRIVILEGES_REQUEST",
  FETCH_ALLPRIVILEGES_SUCCESS = "FETCH_ALLPRIVILEGES_SUCCESS",
  FETCH_ALLPRIVILEGES_FAILURE = "FETCH_ALLPRIVILEGES_FAILURE",
  ALLPRIVILEGES_INFO = "ALLPRIVILEGES_INFO",
}
//user

export enum UserTypes {
  FETCH_USER_REQUEST = "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE = "FETCH_USER_FAILURE",
  USER_INFO = "USER_INFO",
}
//adduser
export enum addUserTypes {
  FETCH_ADDUSER_REQUEST = "FETCH_ADDUSER_REQUEST",
  FETCH_ADDUSER_SUCCESS = "FETCH_ADDUSER_SUCCESS",
  FETCH_ADDUSER_FAILURE = "FETCH_ADDUSER_FAILURE",
  ADDUSER_INFO = "ADDUSER_INFO",
}
//edit user
export enum editUserTypes {
  FETCH_EDITUSER_REQUEST = "FETCH_EDITUSER_REQUEST",
  FETCH_EDITUSER_SUCCESS = "FETCH_EDITUSER_SUCCESS",
  FETCH_EDITUSER_FAILURE = "FETCH_EDITUSER_FAILURE",
  EDITUSER_INFO = "EDITUSER_INFO",
}
//get user
export enum getUserTypes {
  FETCH_GETUSER_REQUEST = "FETCH_GETUSER_REQUEST",
  FETCH_GETUSER_SUCCESS = "FETCH_GETUSER_SUCCESS",
  FETCH_GETUSER_FAILURE = "FETCH_GETUSER_FAILURE",
  GETUSER_INFO = "GETUSER_INFO",
}

//roleset
export enum allRolesetTypes {
  FETCH_ALLROLESET_REQUEST = "FETCH_ALLROLESET_REQUEST",
  FETCH_ALLROLESET_SUCCESS = "FETCH_ALLROLESET_SUCCESS",
  FETCH_ALLROLESET_FAILURE = "FETCH_ALLROLESET_FAILURE",
  ALLALLROLESET_INFO = "ALLROLESET_INFO",
}
//delete user
export enum delUserTypes {
  FETCH_DELUSER_REQUEST = "FETCH_DELUSER_REQUEST",
  FETCH_DELUSER_SUCCESS = "FETCH_DELUSER_SUCCESS",
  FETCH_DELUSER_FAILURE = "FETCH_DELUSER_FAILURE",
  DELUSER_INFO = "DELUSER_INFO",
}

//employers
export enum allEmployersTypes {
  FETCH_ALLEMPLOYERS_REQUEST = "FETCH_ALLEMPLOYERS_REQUEST",
  FETCH_ALLEMPLOYERS_SUCCESS = "FETCH_ALLEMPLOYERS_SUCCESS",
  FETCH_ALLEMPLOYERS_FAILURE = "FETCH_ALLEMPLOYERS_FAILURE",
  ALLEMPLOYERS_INFO = "ALLEMPLOYERS_INFO",
}

export enum editEmployerTypes {
  FETCH_EDITEMPLOYER_REQUEST = "FETCH_EDITEMPLOYER_REQUEST",
  FETCH_EDITEMPLOYER_SUCCESS = "FETCH_EDITEMPLOYER_SUCCESS",
  FETCH_EDITEMPLOYER_FAILURE = "FETCH_EDITEMPLOYER_FAILURE",
  EDITEMPLOYER_INFO = "EDITEMPLOYER_INFO",
}

export enum getEmployerTypes {
  FETCH_GETEMPLOYER_REQUEST = "FETCH_GETEMPLOYER_REQUEST",
  FETCH_GETEMPLOYER_SUCCESS = "FETCH_GETEMPLOYER_SUCCESS",
  FETCH_GETEMPLOYER_FAILURE = "FETCH_GETEMPLOYER_FAILURE",
  GETEMPLOYER_INFO = "GETEMPLOYER_INFO",
}

export enum delEmployerTypes {
  FETCH_DELEMPLOYER_REQUEST = "FETCH_DELEMPLOYER_REQUEST",
  FETCH_DELEMPLOYER_SUCCESS = "FETCH_DELEMPLOYER_SUCCESS",
  FETCH_DELEMPLOYER_FAILURE = "FETCH_DELEMPLOYER_FAILURE",
  DELEMPLOYER_INFO = "DELEMPLOYER_INFO",
}

export enum addEmployerTypes {
  FETCH_ADDEMPLOYER_REQUEST = "FETCH_ADDEMPLOYER_REQUEST",
  FETCH_ADDEMPLOYER_SUCCESS = "FETCH_ADDEMPLOYER_SUCCESS",
  FETCH_ADDEMPLOYER_FAILURE = "FETCH_ADDEMPLOYER_FAILURE",
  ADDEMPLOYER_INFO = "ADDEMPLOYER_INFO",
}

export enum statesTypes {
  FETCH_STATES_REQUEST = "FETCH_STATES_REQUEST",
  FETCH_STATES_SUCCESS = "FETCH_STATES_SUCCESS",
  FETCH_STATES_FAILURE = "FETCH_STATES_FAILURE",
  STATES_INFO = "STATES_INFO",
}

//Employee Details for Create
export enum empDetailsForCreateTypes {
  FETCH_EMPDETAILSFORCREATE_REQUEST = "FETCH_EMPDETAILSFORCREATE_REQUEST",
  FETCH_EMPDETAILSFORCREATE_SUCCESS = "FETCH_EMPDETAILSFORCREATE_SUCCESS",
  FETCH_EMPDETAILSFORCREATE_FAILURE = "FETCH_EMPDETAILSFORCREATE_FAILURE",
  EMPDETAILSFORCREATE_INFO = "EMPDETAILSFORCREATE_INFO",
}

export enum updateEmpQLEStepsTypes {
  FETCH_UPDATEEMPQLESTEPS_REQUEST = "FETCH_UPDATEEMPQLESTEPS_REQUEST",
  FETCH_UPDATEEMPQLESTEPS_SUCCESS = "FETCH_UPDATEEMPQLESTEPS_SUCCESS",
  FETCH_UPDATEEMPQLESTEPS_FAILURE = "FETCH_UPDATEEMPQLESTEPS_FAILURE",
  UPDATEEMPQLESTEPS_INFO = "UPDATEEMPQLESTEPS_INFO",
}

export enum updateEmpQLEStepsEventTypes {
  FETCH_UPDATEEMPQLESTEPSEVENT_REQUEST = "FETCH_UPDATEEMPQLESTEPSEVENT_REQUEST",
  FETCH_UPDATEEMPQLESTEPSEVENT_SUCCESS = "FETCH_UPDATEEMPQLESTEPSEVENT_SUCCESS",
  FETCH_UPDATEEMPQLESTEPSEVENT_FAILURE = "FETCH_UPDATEEMPQLESTEPSEVENT_FAILURE",
  UPDATEEMPQLESTEPSEVENT_INFO = "UPDATEEMPQLESTEPSEVENT_INFO",
}

export enum dashboardTypes {
  FETCH_DASHBOARD_REQUEST = "FETCH_DASHBOARD_REQUEST",
  FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS",
  FETCH_DASHBOARD_FAILURE = "FETCH_DASHBOARD_FAILURE",
  DASHBOARD_INFO = "DASHBOARD_INFO",
}

//QLE All emailTemplates
export enum allQLEEmailTemplateTypes {
  FETCH_ALLQLEEMAILTEMPLATE_REQUEST = "FETCH_ALLQLEEMAILTEMPLATE_REQUEST",
  FETCH_ALLQLEEMAILTEMPLATE_SUCCESS = "FETCH_ALLQLEEMAILTEMPLATE_SUCCESS",
  FETCH_ALLQLEEMAILTEMPLATE_FAILURE = "FETCH_ALLQLEEMAILTEMPLATE_FAILURE",
  ALLQLEEMAILTEMPLATE_INFO = "ALLQLEEMAILTEMPLATE_INFO",
}

// QLE edit email temp
export enum editQLEEmailTemplateTypes {
  FETCH_EDITQLEEMAILTEMPLATE_REQUEST = "FETCH_EDITQLEEMAILTEMPLATE_REQUEST",
  FETCH_EDITQLEEMAILTEMPLATE_SUCCESS = "FETCH_EDITQLEEMAILTEMPLATE_SUCCESS",
  FETCH_EDITQLEEMAILTEMPLATE_FAILURE = "FETCH_EDITQLEEMAILTEMPLATE_FAILURE",
  EDITQLEEMAILTEMPLATE_INFO = "EDITQLEEMAILTEMPLATE_INFO",
}

//QLE GET EMAILTEMPLATES
export enum getQLEEmailTemplateTypes {
  FETCH_GETQLEEMAILTEMPLATE_REQUEST = "FETCH_GETQLEEMAILTEMPLATE_REQUEST",
  FETCH_GETQLEEMAILTEMPLATE_SUCCESS = "FETCH_GETQLEEMAILTEMPLATE_SUCCESS",
  FETCH_GETQLEEMAILTEMPLATE_FAILURE = "FETCH_GETQLEEMAILTEMPLATE_FAILURE",
  GETQLEEMAILTEMPLATE_INFO = "GETQLEEMAILTEMPLATE_INFO",
}

//ACA All emailtemplate
export enum allACAEmailTemplateTypes {
  FETCH_ALLACAEMAILTEMPLATE_REQUEST = "FETCH_ALLACAEMAILTEMPLATE_REQUEST",
  FETCH_ALLACAEMAILTEMPLATE_SUCCESS = "FETCH_ALLACAEMAILTEMPLATE_SUCCESS",
  FETCH_ALLACAEMAILTEMPLATE_FAILURE = "FETCH_ALLACAEMAILTEMPLATE_FAILURE",
  ALLACAEMAILTEMPLATE_INFO = "ALLACAEMAILTEMPLATE_INFO",
}
// get ACA EmailTemplate
export enum getACAEmailTemplateTypes {
  FETCH_GETACAEMAILTEMPLATE_REQUEST = "FETCH_GETACAEMAILTEMPLATE_REQUEST",
  FETCH_GETACAEMAILTEMPLATE_SUCCESS = "FETCH_GETACAEMAILTEMPLATE_SUCCESS",
  FETCH_GETACAEMAILTEMPLATE_FAILURE = "FETCH_GETACAEMAILTEMPLATE_FAILURE",
  GETACAEMAILTEMPLATE_INFO = "GETACAEMAILTEMPLATE_INFO",
}

// ACA edit email temp
export enum editACAEmailTemplateTypes {
  FETCH_EDITACAEMAILTEMPLATE_REQUEST = "FETCH_EDITACAEMAILTEMPLATE_REQUEST",
  FETCH_EDITACAEMAILTEMPLATE_SUCCESS = "FETCH_EDITACAEMAILTEMPLATE_SUCCESS",
  FETCH_EDITACAEMAILTEMPLATE_FAILURE = "FETCH_EDITACAEMAILTEMPLATE_FAILURE",
  EDITACAEMAILTEMPLATE_INFO = "EDITACAEMAILTEMPLATE_INFO",
}

// get ACA messaageTemplate
export enum getACAMessageTemplateTypes {
  FETCH_GETACAMESSAGETEMPLATE_REQUEST = "FETCH_GETACAMESSAGETEMPLATE_REQUEST",
  FETCH_GETACAMESSAGETEMPLATE_SUCCESS = "FETCH_GETACAMESSAGETEMPLATE_SUCCESS",
  FETCH_GETACAMESSAGETEMPLATE_FAILURE = "FETCH_GETACAMESSAGETEMPLATE_FAILURE",
  GETACAMESSAGETEMPLATE_INFO = "GETACAMESSAGETEMPLATE_INFO",
}
// ACA edit message temp
export enum editACAMessageTemplateTypes {
  FETCH_EDITACAMESSAGETEMPLATE_REQUEST = "FETCH_EDITACAMESSAGETEMPLATE_REQUEST",
  FETCH_EDITACAMESSAGETEMPLATE_SUCCESS = "FETCH_EDITACAMESSAGETEMPLATE_SUCCESS",
  FETCH_EDITACAMESSAGETEMPLATE_FAILURE = "FETCH_EDITACAMESSAGETEMPLATE_FAILURE",
  EDITACAMESSAGETEMPLATE_INFO = "EDITACAMESSAGETEMPLATE_INFO",
}

// get QLE messaageTemplate
export enum getQLEMessageTemplateTypes {
  FETCH_GETQLEMESSAGETEMPLATE_REQUEST = "FETCH_GETQLEMESSAGETEMPLATE_REQUEST",
  FETCH_GETQLEMESSAGETEMPLATE_SUCCESS = "FETCH_GETQLEMESSAGETEMPLATE_SUCCESS",
  FETCH_GETQLEMESSAGETEMPLATE_FAILURE = "FETCH_GETQLEMESSAGETEMPLATE_FAILURE",
  GETQLEMESSAGETEMPLATE_INFO = "GETQLEMESSAGETEMPLATE_INFO",
}

// QLE edit message temp
export enum editQLEMessageTemplateTypes {
  FETCH_EDITQLEMESSAGETEMPLATE_REQUEST = "FETCH_EDITQLEMESSAGETEMPLATE_REQUEST",
  FETCH_EDITQLEMESSAGETEMPLATE_SUCCESS = "FETCH_EDITQLEMESSAGETEMPLATE_SUCCESS",
  FETCH_EDITQLEMESSAGETEMPLATE_FAILURE = "FETCH_EDITQLEMESSAGETEMPLATE_FAILURE",
  EDITQLEMESSAGETEMPLATE_INFO = "EDITQLEMESSAGETEMPLATE_INFO",
}

// QLE FAQ
export enum allQleFaqsTypes {
  FETCH_ALLQLEFAQS_REQUEST = "FETCH_ALLQLEFAQS_REQUEST",
  FETCH_ALLQLEFAQS_SUCCESS = "FETCH_ALLQLEFAQS_SUCCESS",
  FETCH_ALLQLEFAQS_FAILURE = "FETCH_ALLQLEFAQS_FAILURE",
  ALLQLEFAQS_INFO = "ALLQLEFAQS_INFO",
}

//edit faq
export enum editFaqTypes {
  FETCH_EDITFAQ_REQUEST = "FETCH_EDITFAQ_REQUEST",
  FETCH_EDITFAQ_SUCCESS = "FETCH_EDITFAQ_SUCCESS",
  FETCH_EDITFAQ_FAILURE = "FETCH_EDITFAQ_FAILURE",
  EDITFAQ_INFO = "EDITFAQ_INFO",
}

//addFaq
export enum addFaqTypes {
  FETCH_ADDFAQ_REQUEST = "FETCH_ADDFAQ_REQUEST",
  FETCH_ADDFAQ_SUCCESS = "FETCH_ADDFAQ_SUCCESS",
  FETCH_ADDFAQ_FAILURE = "FETCH_ADDFAQ_FAILURE",
  ADDFAQ_INFO = "ADDFAQ_INFO",
}

//get Faq
export enum getFaqTypes {
  FETCH_GETFAQ_REQUEST = "FETCH_GETFAQ_REQUEST",
  FETCH_GETFAQ_SUCCESS = "FETCH_GETFAQ_SUCCESS",
  FETCH_GETFAQ_FAILURE = "FETCH_GETFAQ_FAILURE",
  GETFAQ_INFO = "GETFAQ_INFO",
}

// del faq
export enum delFaqTypes {
  FETCH_DELFAQ_REQUEST = "FETCH_DELFAQ_REQUEST",
  FETCH_DELFAQ_SUCCESS = "FETCH_DELFAQ_SUCCESS",
  FETCH_DELFAQ_FAILURE = "FETCH_DELFAQ_FAILURE",
  DELFAQ_INFO = "DELFAQ_INFO",
}

export enum allFaqsByEmployerTypes {
  FETCH_ALLFAQSBYEMP_REQUEST = "FETCH_ALLFAQSBYEMP_REQUEST",
  FETCH_ALLFAQSBYEMP_SUCCESS = "FETCH_ALLFAQSBYEMP_SUCCESS",
  FETCH_ALLFAQSBYEMP_FAILURE = "FETCH_ALLFAQSBYEMP_FAILURE",
  ALLFAQSBYEMP_INFO = "ALLFAQSBYEMP_INFO",
}

export enum allReOrderedFaqsTypes {
  FETCH_ALLREORDEREDFAQS_REQUEST = "FETCH_ALLREORDEREDFAQS_REQUEST",
  FETCH_ALLREORDEREDFAQS_SUCCESS = "FETCH_ALLREORDEREDFAQS_SUCCESS",
  FETCH_ALLREORDEREDFAQS_FAILURE = "FETCH_ALLREORDEREDFAQS_FAILURE",
  ALLREORDEREDFAQS_INFO = "ALLREORDEREDFAQS_INFO",
}

export enum allqlesTypes {
  FETCH_ALLQLES_REQUEST = "FETCH_ALLQLES_REQUEST",
  FETCH_ALLQLES_SUCCESS = "FETCH_ALLQLES_SUCCESS",
  FETCH_ALLQLES_FAILURE = "FETCH_ALLQLES_FAILURE",
  ALLQLES_INFO = "ALLQLES_INFO",
}

export enum allACATypes {
  FETCH_ALLACA_REQUEST = "FETCH_ALLACA_REQUEST",
  FETCH_ALLACA_SUCCESS = "FETCH_ALLACA_SUCCESS",
  FETCH_ALLACA_FAILURE = "FETCH_ALLACA_FAILURE",
  ALLACA_INFO = "ALLACA_INFO",
}

export enum getACAEventTypes {
  FETCH_GETACAEVENT_REQUEST = "FETCH_GETACAEVENT_REQUEST",
  FETCH_GETACAEVENT_SUCCESS = "FETCH_GETACAEVENT_SUCCESS",
  FETCH_GETACAEVENT_FAILURE = "FETCH_GETACAEVENT_FAILURE",
  GETACAEVENT_INFO = "GETACAEVENT_INFO",
}

export enum editACAInfoTypes {
  FETCH_EDITACAINFO_REQUEST = " FETCH_EDITACAINFO_REQUEST",
  FETCH_EDITACAINFO_SUCCESS = " FETCH_EDITACAINFO_SUCCESS",
  FETCH_EDITACAINFO_FAILURE = " FETCH_EDITACAINFO_FAILURE",
  EDITACAINFO_INFO = "EDITACAINFO_INFO",
}

export enum delACAEventTypes {
  FETCH_DELACAEVENT_REQUEST = "FETCH_DELACAEVENT_REQUEST",
  FETCH_DELACAEVENT_SUCCESS = "FETCH_DELACAEVENT_SUCCESS",
  FETCH_DELACAEVENT_FAILURE = "FETCH_DELACAEVENT_FAILURE",
  DELACAEVENT_INFO = "DELACAEVENT_INFO",
}

export enum employerACATypes {
  FETCH_EMPLOYERACA_REQUEST = " FETCH_EMPLOYERACA_REQUEST",
  FETCH_EMPLOYERACA_SUCCESS = " FETCH_EMPLOYERACA_SUCCESS",
  FETCH_EMPLOYERACA_FAILURE = " FETCH_EMPLOYERACA_FAILURE",
  EMPLOYERACA_INFO = "EMPLOYERACA_INFO",
}

//employerACAEdit
export enum employerACAEditTypes {
  FETCH_EMPLOYERACAEDIT_REQUEST = "FETCH_EMPLOYERACAEDIT_REQUEST",
  FETCH_EMPLOYERACAEDIT_SUCCESS = "FETCH_EMPLOYERACAEDIT_SUCCESS",
  FETCH_EMPLOYERACAEDIT_FAILURE = "FETCH_EMPLOYERACAEDIT_FAILURE",
  EMPLOYERACAEDIT_INFO = "EMPLOYERACAEDIT_INFO",
}

//editinfo
export enum editInfoTypes {
  FETCH_EDIT_REQUEST = "FETCH_EDIT_REQUEST",
  FETCH_EDIT_SUCCESS = "FETCH_EDIT_SUCCESS",
  FETCH_EDIT_FAILURE = "FETCH_EDIT_FAILURE",
  EDIT_INFO = "EDIT_INFO",
}

//notes
export enum notesTypes {
  FETCH_NOTES_REQUEST = "FETCH_NOTES_REQUEST",
  FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS",
  FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE",
  NOTES_INFO = "NOTES_INFO",
}

//getEditInfo
export enum getEditByIdTypes {
  FETCH_GETEDITBYID_REQUEST = "FETCH_GETEDITBYID_REQUEST",
  FETCH_GETEDITBYID_SUCCESS = "FETCH_GETEDITBYID_SUCCESS",
  FETCH_GETEDITBYID_FAILURE = "FETCH_GETEDITBYID_FAILURE",
  GETEDITBYID_INFO = "GETEDITBYID__INFO",
}

//SentStatusMail
export enum sentStatusMailTypes {
  FETCH_SENTSTATUSMAIL_REQUEST = "FETCH_SENTSTATUSMAIL_REQUEST",
  FETCH_SENTSTATUSMAIL_SUCCESS = "FETCH_SENTSTATUSMAIL_SUCCESS",
  FETCH_SENTSTATUSMAIL_FAILURE = "FETCH_SENTSTATUSMAIL_FAILURE",
  SENTSTATUSMAIL__INFO = "SENTSTATUSMAIL__INFO",
}

//Files
export enum filesTypes {
  FETCH_FILES_REQUEST = "FETCH_FILES_REQUEST",
  FETCH_FILES_SUCCESS = "FETCH_FILES_SUCCESS",
  FETCH_FILES_FAILURE = "FETCH_FILES_FAILURE",
  FILES_INFO = "FILES_INFO",
}

//filesview
export enum filesViewTypes {
  FETCH_FILESVIEW_REQUEST = "FETCH_FILESVIEW_REQUEST",
  FETCH_FILESVIEW_SUCCESS = "FETCH_FILESVIEW_SUCCESS",
  FETCH_FILESVIEW_FAILURE = "FETCH_FILESVIEW_FAILURE",
  FILESVIEW_INFO = "FILESVIEW_INFO",
}

//filesdelete
export enum filesDeleteTypes {
  FETCH_DELETEFILES_REQUEST = "FETCH_DELETEFILES_REQUEST",
  FETCH_DELETEFILES_SUCCESS = "FETCH_DELETEFILES_SUCCESS",
  FETCH_DELETEFILESE_FAILURE = "FETCH_DELETEFILES_FAILURE",
  DELETEFILESE_INFO = "DELETEFILES_INFO",
}

//Delete event
export enum delQleEventTypes {
  FETCH_DELQLEEVENT_REQUEST = "FETCH_DELQLEEVENT_REQUEST",
  FETCH_DELQLEEVENT_SUCCESS = "FETCH_DELQLEEVENT_SUCCESS",
  FETCH_DELQLEEVENT_FAILURE = "FETCH_DELQLEEVENT_FAILURE",
  DELQLEEVENT_INFO = "DELQLEEVENT_INFO",
}

//communication
export enum communicationTypes {
  FETCH_COMMUNICATION_REQUEST = "FETCH_COMMUNICATION_REQUEST",
  FETCH_COMMUNICATION_SUCCESS = "FETCH_COMMUNICATION_SUCCESS",
  FETCH_COMMUNICATION_FAILURE = "FETCH_COMMUNICATION_FAILURE",
  COMMUNICATION_INFO = "COMMUNICATION_INFO",
}

//ADD Note

export enum addNoteTypes {
  FETCH_ADDNOTE_REQUEST = "FETCH_ADDNOTE_REQUEST",
  FETCH_ADDNOTE_SUCCESS = "FETCH_ADDNOTE_SUCCESS",
  FETCH_ADDNOTE_FAILURE = "FETCH_ADDNOTE_FAILURE",
  ADDNOTE_INFO = "ADDNOTE_INFO",
}

//ADD email Phonelog

export enum addEmailTypes {
  FETCH_ADDEMAIL_REQUEST = "FETCH_ADDEMAIL_REQUEST",
  FETCH_ADDEMAIL_SUCCESS = "FETCH_ADDEMAIL_SUCCESS",
  FETCH_ADDEMAIL_FAILURE = "FETCH_ADDEMAIL_FAILURE",
  ADDEMAIL_INFO = "ADDEMAIL_INFO",
}

// User Profile
export enum getUserProfileTypes {
  FETCH_GETUSERPROFILE_REQUEST = "FETCH_GETUSERPROFILE_REQUEST",
  FETCH_GETUSERPROFILE_SUCCESS = "FETCH_GETUSERPROFILE_SUCCESS",
  FETCH_GETUSERPROFILE_FAILURE = "FETCH_GETUSERPROFILE_FAILURE",
  GETUSERPROFILE_INFO = "GETUSERPROFILE_INFO",
}

// edit userprofile
export enum editUserProfileTypes {
  FETCH_EDITUSERPROFILE_REQUEST = "FETCH_EDITUSERPROFILE_REQUEST",
  FETCH_EDITUSERPROFILE_SUCCESS = "FETCH_EDITUSERPROFILE_SUCCESS",
  FETCH_EDITUSERPROFILE_FAILURE = "FETCH_EDITUSERPROFILE_FAILURE",
  EDITUSERPROFILE_INFO = "EDITUSERPROFILE_INFO",
}

// change userprofile
export enum changeUserProfilePasswordTypes {
  FETCH_CHANGEUSERPROFILE_REQUEST = "FETCH_CHANGEUSERPROFILE_REQUEST",
  FETCH_CHANGEUSERPROFILE_SUCCESS = "FETCH_CHANGEUSERPROFILE_SUCCESS",
  FETCH_CHANGEUSERPROFILE_FAILURE = "FETCH_CHANGEUSERPROFILE_FAILURE",
  CHANGEUSERPROFILE_INFO = "CHANGEUSERPROFILE_INFO",
}

// Employer ACA edit health plan
export enum empHealthPlanTypes {
  FETCH_EMPHEALTHPLAN_REQUEST = "FETCH_EMPHEALTHPLAN_REQUEST",
  FETCH_EMPHEALTHPLAN_SUCCESS = "FETCH_EMPHEALTHPLAN_SUCCESS",
  FETCH_EMPHEALTHPLAN_FAILURE = "FETCH_EMPHEALTHPLAN_FAILURE",
  EMPHEALTHPLAN_INFO = "EMPHEALTHPLAN_INFO",
}

//Employer ACA edit Newyear changes
export enum empNewYearPlanTypes {
  FETCH_EMPNEWYEARPLAN_REQUEST = "FETCH_EMPNEWYEARPLAN_REQUEST",
  FETCH_EMPNEWYEARPLAN_SUCCESS = "FETCH_EMPNEWYEARPLAN_SUCCESS",
  FETCH_EMPNEWYEARPLAN_FAILURE = "FETCH_EMPNEWYEARPLAN_FAILURE",
  EMPNEWYEARPLAN_INFO = "EMPNEWYEARPLAN_INFO",
}

//Employer ACA eligibility
export enum empEligibilityTypes {
  FETCH_EMP_ELIGIBILITY_REQUEST = "FETCH_EMP_ELIGIBILITY_REQUEST",
  FETCH_EMP_ELIGIBILITY_SUCCESS = "FETCH_EMP_ELIGIBILITY_SUCCESS",
  FETCH_EMP_ELIGIBILITY_FAILURE = "FETCH_EMP_ELIGIBILITY_FAILURE",
  EMP_ELIGIBILITY_INFO = "EMP_ELIGIBILITY_INFO",
}

//healthPlan
export enum healthPlanTypes {
  FETCH_HEALTHPLAN_REQUEST = "FETCH_HEALTHPLAN_REQUEST",
  FETCH_HEALTHPLAN_SUCCESS = "FETCH_HEALTHPLAN_SUCCESS",
  FETCH_HEALTHPLAN_FAILURE = "FETCH_HEALTHPLAN_FAILURE",
  HEALTHPLAN_INFO = "HEALTHPLAN_INFO",
}

//healthPlanUpdate
export enum editHealthPlanTypes {
  FETCH_EDITHEALTHPLAN_REQUEST = "FETCH_EDITHEALTHPLAN_REQUEST",
  FETCH_EDITHEALTHPLAN_SUCCESS = "FETCH_EDITHEALTHPLAN_SUCCESS",
  FETCH_EDITHEALTHPLAN_FAILURE = "FETCH_EDITHEALTHPLAN_FAILURE",
  EDITHEALTHPLAN_INFO = "EDITHEALTHPLAN_INFO",
}

//eligibility
export enum eligibilityTypes {
  FETCH_ELIGIBILITY_REQUEST = "FETCH_ELIGIBILITY_REQUEST",
  FETCH_ELIGIBILITY_SUCCESS = "FETCH_ELIGIBILITY_SUCCESS",
  FETCH_ELIGIBILITY_FAILURE = "FETCH_ELIGIBILITY_FAILURE",
  ELIGIBILITY_INFO = "ELIGIBILITY_INFO",
}

//newYear Plan changes
export enum newYearPlanTypes {
  FETCH_NEWYEARPLAN_REQUEST = "FETCH_NEWYEARPLAN_REQUEST",
  FETCH_NEWYEARPLAN_SUCCESS = "FETCH_NEWYEARPLAN_SUCCESS",
  FETCH_NEWYEARPLAN_FAILURE = "FETCH_NEWYEARPLAN_FAILURE",
  NEWYEARPLAN_INFO = "NEWYEARPLAN_INFO",
}

//aca preview
export enum getACAPreviewTypes {
  FETCH_GET_ACA_PREVIEW_REQUEST = "FETCH_GET_ACA_PREVIEW_REQUEST",
  FETCH_GET_ACA_PREVIEW_SUCCESS = "FETCH_GET_ACA_PREVIEW_SUCCESS",
  FETCH_GET_ACA_PREVIEW_FAILURE = "FETCH_GET_ACA_PREVIEW_FAILURE",
  GET_ACA_PREVIEW_INFO = "GET_ACA_PREVIEW_INFO",
}

//ACA download pdf
export enum getACADownloadTypes {
  FETCH_GET_ACA_DOWNLOAD_REQUEST = "FETCH_GET_ACA_DOWNLOAD_REQUEST",
  FETCH_GET_ACA_DOWNLOAD_SUCCESS = "FETCH_GET_ACA_DOWNLOAD_SUCCESS",
  FETCH_GET_ACA_DOWNLOAD_FAILURE = "FETCH_GET_ACA_DOWNLOAD_FAILURE",
  GET_ACA_DOWNLOAD_INFO = "GET_ACADOWNLOAD_INFO",
}

//ACA email pdf
export enum getACAEmailTypes {
  FETCH_GET_ACA_EMAIL_REQUEST = "FETCH_GET_ACA_EMAIL_REQUEST",
  FETCH_GET_ACA_EMAIL_SUCCESS = "FETCH_GET_ACA_EMAIL_SUCCESS",
  FETCH_GET_ACA_EMAIL_FAILURE = "FETCH_GET_ACA_EMAIL_FAILURE",
  GET_ACA_EMAIL_INFO = "GET_ACA_EMAIL_INFO",
}

export enum dailyProductivityReportTypes {
  FETCH_DAILY_PROD_REPORT_REQUEST = "FETCH_DAILY_PROD_REPORT_REQUEST",
  FETCH_DAILY_PROD_REPORT_SUCCESS = "FETCH_DAILY_PROD_REPORT_SUCCESS",
  FETCH_DAILY_PROD_REPORT_FAILURE = "FETCH_DAILY_PROD_REPORT_FAILURE",
  DAILY_PROD_REPORT_INFO = "DAILY_PROD_REPORT_INFO",
}

export enum allActiveEmployersTypes {
  FETCH_ALLACTIVEEMPLOYERS_REQUEST = "FETCH_ALLACTIVEEMPLOYERS_REQUEST",
  FETCH_ALLACTIVEEMPLOYERS_SUCCESS = "FETCH_ALLACTIVEEMPLOYERS_SUCCESS",
  FETCH_ALLACTIVEEMPLOYERS_FAILURE = "FETCH_ALLACTIVEEMPLOYERS_FAILURE",
  ALLACTIVEEMPLOYERS_INFO = "ALLACTIVEEMPLOYERS_INFO",
}

export enum quantitiesReportTypes {
  FETCH_QUANTITIES_REPORT_REQUEST = "FETCH_QUANTITIES_REPORT_REQUEST",
  FETCH_QUANTITIES_REPORT_SUCCESS = "FETCH_QUANTITIES_REPORT_SUCCESS",
  FETCH_QUANTITIES_REPORT_FAILURE = "FETCH_QUANTITIES_REPORT_FAILURE",
  QUANTITIES_REPORT_INFO = "QUANTITIES_REPORT_INFO",
}

export enum quantitiesReportDownloadTypes {
  FETCH_QUANTITIES_DOWNLOAD_REPORT_REQUEST = "FETCH_QUANTITIES_DOWNLOAD_REPORT_REQUEST",
  FETCH_QUANTITIES_DOWNLOAD_REPORT_SUCCESS = "FETCH_QUANTITIES_DOWNLOAD_REPORT_SUCCESS",
  FETCH_QUANTITIES_DOWNLOAD_REPORT_FAILURE = "FETCH_QUANTITIES_DOWNLOAD_REPORT_FAILURE",
  QUANTITIES_REPORT_DOWNLOAD_INFO = "QUANTITIES_DOWNLOAD_REPORT_INFO",
}

export enum sLAReportTypes {
  FETCH_SLA_REPORT_REQUEST = "FETCH_SLA_REPORT_REQUEST",
  FETCH_SLA_REPORT_SUCCESS = "FETCH_SLA_REPORT_SUCCESS",
  FETCH_SLA_REPORT_FAILURE = "FETCH_SLA_REPORT_FAILURE",
  SLA_REPORT_INFO = "SLA_REPORT_INFO",
}

export enum agingReportTypes {
  FETCH_AGING_REPORT_REQUEST = "FETCH_AGING_REPORT_REQUEST",
  FETCH_AGING_REPORT_SUCCESS = "FETCH_AGING_REPORT_SUCCESS",
  FETCH_AGING_REPORT_FAILURE = "FETCH_AGING_REPORT_FAILURE",
  AGING_REPORT_INFO = "AGING_REPORT_INFO",
}

export enum dailyProductivityReportDownloadTypes {
  FETCH_DAILY_PROD_REPORT_DOWNLOAD_REQUEST = "FETCH_DAILY_PROD_REPORT_DOWNLOAD_REQUEST",
  FETCH_DAILY_PROD_REPORT_DOWNLOAD_SUCCESS = "FETCH_DAILY_PROD_REPORT_DOWNLOAD_SUCCESS",
  FETCH_DAILY_PROD_REPORT_DOWNLOAD_FAILURE = "FETCH_DAILY_PROD_REPORT_DOWNLOAD_FAILURE",
  DAILY_PROD_REPORT_DOWNLOAD_INFO = "DAILY_PROD_REPORT_DOWNLOAD_INFO",
}

export enum sLAReportDownloadTypes {
  FETCH_SLA_REPORT_DOWNLOAD_REQUEST = "FETCH_SLA_REPORT_DOWNLOAD_REQUEST",
  FETCH_SLA_REPORT_DOWNLOAD_SUCCESS = "FETCH_SLA_REPORT_DOWNLOAD_SUCCESS",
  FETCH_SLA_REPORT_DOWNLOAD_FAILURE = "FETCH_SLA_REPORT_DOWNLOAD_FAILURE",
  SLA_REPORT_DOWNLOAD_INFO = "SLA_REPORT_DOWNLOAD_INFO",
}

export enum agingReportDownloadTypes {
  FETCH_AGING_REPORT_DOWNLOAD_REQUEST = "FETCH_AGING_REPORT_DOWNLOAD__REQUEST",
  FETCH_AGING_REPORT_DOWNLOAD_SUCCESS = "FETCH_AGING_REPORT_DOWNLOAD__SUCCESS",
  FETCH_AGING_REPORT_DOWNLOAD_FAILURE = "FETCH_AGING_REPORT_DOWNLOAD__FAILURE",
  AGING_REPORT_DOWNLOAD_INFO = "AGING_REPORT_DOWNLOAD__INFO",
}

//download Holiday Template
export enum downloadHolidayTemp {
  FETCH_DOWNLOAD_HOLIDAY_TEMP_REQUEST = "FETCH_DOWNLOAD_HOLIDAY_TEMP_REQUEST",
  FETCH_DOWNLOAD_HOLIDAY_TEMP_SUCCESS = "FETCH_DOWNLOAD_HOLIDAY_TEMP_SUCCESS",
  FETCH_DOWNLOAD_HOLIDAY_TEMP_FAILURE = "FETCH_DOWNLOAD_HOLIDAY_TEMP_FAILURE",
  DOWNLOAD_HOLIDAY_TEMP_INFO = "DOWNLOAD_HOLIDAY_TEMP_INFO",
}

// getHolidayList
export enum getHolidayListTypes {
  FETCH_GET_HOLIDAY_LIST_REQUEST = "FETCH_GET_HOLIDAY_LIST_REQUEST",
  FETCH_GET_HOLIDAY_LIST_SUCCESS = "FETCH_GET_HOLIDAY_LIST_SUCCESS",
  FETCH_GET_HOLIDAY_LIST_FAILURE = "FETCH_GET_HOLIDAY_LIST_FAILURE",
  GET_HOLIDAY_LIST_INFO = "GET_HOLIDAY_LIST_INFO",
}

// uploadHolidayList
export enum uploadHolidayListTypes {
  FETCH_UPLOAD_HOLIDAY_LIST_REQUEST = "FETCH_UPLOAD_HOLIDAY_LIST_REQUEST",
  FETCH_UPLOAD_HOLIDAY_LIST_SUCCESS = "FETCH_UPLOAD_HOLIDAY_LIST_SUCCESS",
  FETCH_UPLOAD_HOLIDAY_LIST_FAILURE = "FETCH_UPLOAD_HOLIDAY_LIST_FAILURE",
  UPLOAD_HOLIDAY_LIST_INFO = "UPLOAD_HOLIDAY_LIST_INFO",
}

// upload Image
export enum uploadImageTypes {
  FETCH_UPLOADIMAGE_REQUEST = "FETCH_UPLOADIMAGE_REQUEST",
  FETCH_UPLOADIMAGE_SUCCESS = "FETCH_UPLOADIMAGE_SUCCESS",
  FETCH_UPLOADIMAGE_FAILURE = "FETCH_UPLOADIMAGE_FAILURE",
  UPLOADIMAGE_INFO = "UPLOADIMAGE_INFO"
}

// get Uploadimage
export enum getUploadImageTypes {
  FETCH_GET_UPLOADIMAGE_REQUEST = "FETCH_GET_UPLOADIMAGE_REQUEST",
  FETCH_GET_UPLOADIMAGE_SUCCESS = "FETCH_GET_UPLOADIMAGE_SUCCESS",
  FETCH_GET_UPLOADIMAGE_FAILURE = "FETCH_GET_UPLOADIMAGE_FAILURE",
  GET_UPLOADIMAGE_INFO = "GET_UPLOADIMAGE_INFO",
}

// Logout
export enum logOutTypes {
  FETCH_LOGOUT_REQUEST = "FETCH_LOGOUT_REQUEST",
  FETCH_LOGOUT_SUCCESS = "FETCH_LOGOUT_SUCCESS",
  FETCH_LOGOUT_FAILURE = "FETCH_LOGOUT_FAILURE",
  LOGOUT_INFO = "LOGOUT_INFO",
}

export enum ActiveUserTypes {
  FETCH_ACTIVE_USER_REQUEST = "FETCH_ACTIVE_USER_REQUEST",
  FETCH_ACTIVE_USER_SUCCESS = "FETCH_ACTIVE_USER_SUCCESS",
  FETCH_ACTIVE_USER_FAILURE = "FETCH_ACTIVE_USER_FAILURE",
  ACTIVE_USER_INFO = "ACTIVE_USER_INFO",
}

export enum getActiveUserTypes {
  FETCH_ACTIVE_USER_REQUEST = "FETCH_ACTIVE_USER_REQUEST",
  FETCH_ACTIVE_USER_SUCCESS = "FETCH_ACTIVE_USER_SUCCESS",
  FETCH_ACTIVE_USER_FAILURE = "FETCH_ACTIVE_USER_FAILURE",
  ACTIVE_USER_INFO = "ACTIVE_USER_INFO",
}

export enum eventStatusTypes {
  FETCH_EVENT_STATUS_REQUEST = "FETCH_EVENT_STATUS_REQUEST",
  FETCH_EVENT_STATUS_SUCCESS = "FETCH_EVENT_STATUS_SUCCESS",
  FETCH_EVENT_STATUS_FAILURE = "FETCH_EVENT_STATUS_FAILURE",
  EVENT_STATUS_INFO = "EVENT_STATUS_INFO",
}